---
platform: linux

inputs:
- name: ci
- name: toolsmiths-env

outputs:
- name: built-acceptance-test-configs

params:
  CONFIGS:
  ENVS:

run:
  path: ci/shared/tasks/build-acceptance-test-configs/task.bash
