---
platform: linux

inputs:
- name: ci
- name: repo
- name: toolsmiths-env
- name: cf-deployment

outputs:
- name: prepared-env
- name: versioned-cf-deployment

params:
  FUNCTIONS:
run:
  path: ci/shared/tasks/run-bin-prepare-cf-deployment-env/task.bash
