---
platform: linux

inputs:
  - name: ci
  - name: source-branch
  - name: onto-branch

outputs:
  - name: merged-branch

run:
  path: ci/shared/tasks/merge-branches/task.bash

params:
  SOURCE_BRANCH_NAME: 
  ONTO_BRANCH_NAME: 
