---
platform: linux

inputs:
- name: ci
- name: repo

outputs:
- name: built-binaries

params:
  DEBUG: false
  FUNCTIONS:
  MAPPING:
  DEFAULT_PARAMS:

run:
  path: ci/shared/tasks/build-binaries/task.bash
