---
platform: linux

inputs:
  - name: ci
  - name: repo
  - name: previous-github-release
  - name: version
  - name: bosh-job-diff
    optional: true #some releases (e.g. cpu entitlement) don't have this

outputs:
  - name: built-release-notes

run:
  path: ci/shared/tasks/build-release-notes/task.bash

params:
  RELEASE_NAME:
