---
platform: linux

inputs:
  - name: ci
  - name: repo
  - name: dep-local-repo-replace-01
    optional: true
  - name: dep-local-repo-replace-02
    optional: true
  - name: dep-local-repo-replace-03
    optional: true
  - name: dep-local-repo-replace-04
    optional: true
  - name: dep-local-repo-replace-05
    optional: true

outputs:
  - name: bumped-repo

params:
  GOOS:
  GO_MODS: # e.g. |
    # src/code.cloudfoundry.org/go.mod
  REPLACE_DIRECTIVES: # e.g. |
    # dep-local-repo-replace-01:garden
  EXTRA_GO_TAGS: #e.g. |
    # tools
    # modules

run:
  path: ci/shared/tasks/bump-dependencies-go-mod/linux.yml
