---
platform: linux

inputs:
- name: ci
- name: repo
- name: built-binaries
  optional: true
- name: input-01
  optional: true

params:
  DEBUG: false
  DEFAULT_PARAMS:
  DIR:
  ENVS:
  FLAGS: |
    --keep-going
    --trace
    -r
    --fail-on-pending
    --randomize-all
    -p
    --race
    --timeout 20m
  FUNCTIONS:
  VERIFICATIONS: |
    verify_go
    verify_gofmt
    verify_govet
run:
  path: ci/shared/tasks/run-bin-test/task.bash
