---
platform: linux

inputs:
- name: ci
- name: repo
- name: built-binaries
  optional: true

params:
  DIR:
  DEBUG: false
  ENVS: #|
    # ENV_KEY=ENV_VALUE
  FUNCTIONS: #|
    #PATH-To-FUNCTIONS-BASH
  VERIFICATIONS: |
    verify_go
    verify_gofmt
    verify_govet

run:
  path: ci/shared/tasks/run-bin-test/task.bash
