---
platform: windows

inputs:
- name: ci
- name: repo
- name: built-binaries
  optional: true
- name: input-01
  optional: true

params:
  DEBUG: false
  DIR:
  ENVS:
  FUNCTIONS:
  VERIFICATIONS: |
    Verify-Go
    Verify-Ginkgo
    Verify-GoVet

run:
  path: powershell
  args:
  - "-ExecutionPolicy"
  - "Bypass"
  - "-File"
  - ci/shared/tasks/run-bin-test/task.ps1

