---
platform: linux

inputs:
  - name: ci
  - name: repo
  - name: toolsmiths-env
  - name: release-01 
    optional: true

params:
  MANIFEST:
  DEPLOYMENT_NAME:
  ENVS:

run:
  path: ci/shared/tasks/bosh-deploy-manifest/task.bash
